print("Hello world")
print("H3llo world")
print("H3ll0 world")
print("He||o world")
print("He11o world")
print("Hel1o world")
print("Hel10 wor/d")
print("H:llo wor|d")
print("H:11o wor1d")
print("Hcllo world")
print("He\\\\o world")
print("He//o world")
print("Hello  world")
print(" Hello world")