print("`\tgrave accent, backtick, back quote")
print("~\ttilde")
print("!\texclamation mark")
print("@\tat sign")
print("#\tsharp")
print("$\tdollar sign")
print("%\tpercent sign")
print("^\tcarat")
print("&\tand, ampersand")
print("*\tasterisk, multiply")
print("(\topen parenthesis, left parenthesis")
print(")\tclose parenthesis, right parenthesis")
print("( )\tparentheses, round brackets")
print("-\thyphen, minus sign, dash")
print("_\tunderscore")
print("=\tequal sign")
print("+\tplus sign")
print(";\tsemicolon")
print(":\tcolon")
print(",\tcomma")
print("{\topen curry bracket")
print("}\tclose curry bracket")
print("|\tvertical bar")
print("/\tslash")
print("\\\tbackslash")
print(".\tdot")
print("<\tless than")
print(">\tgreater than")
print("'\tsingle quote")
print('"\tdouble quote')